#ifdef __CLING__
#pragma cling optimize(0)
#endif
void electron_theta_aftercut()
{
//=========Macro generated from canvas: c1/
//=========  (Thu Oct 24 12:54:05 2024) by ROOT version 6.30/04
   TCanvas *c1 = new TCanvas("c1", "",0,0,800,600);
   gStyle->SetOptFit(1);
   c1->SetHighLightColor(2);
   c1->Range(-5.526316,-654.0632,40.52632,4796.463);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLeftMargin(0.12);
   c1->SetRightMargin(0.12);
   c1->SetTopMargin(0.12);
   c1->SetBottomMargin(0.12);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *electron_theta_aftercut__4 = new TH1F("electron_theta_aftercut__4","",200,0,35);
   electron_theta_aftercut__4->SetBinContent(30,8);
   electron_theta_aftercut__4->SetBinContent(31,599);
   electron_theta_aftercut__4->SetBinContent(32,2092);
   electron_theta_aftercut__4->SetBinContent(33,2007);
   electron_theta_aftercut__4->SetBinContent(34,1771);
   electron_theta_aftercut__4->SetBinContent(35,3202);
   electron_theta_aftercut__4->SetBinContent(36,3419);
   electron_theta_aftercut__4->SetBinContent(37,3452);
   electron_theta_aftercut__4->SetBinContent(38,3416);
   electron_theta_aftercut__4->SetBinContent(39,3394);
   electron_theta_aftercut__4->SetBinContent(40,3180);
   electron_theta_aftercut__4->SetBinContent(41,3311);
   electron_theta_aftercut__4->SetBinContent(42,3129);
   electron_theta_aftercut__4->SetBinContent(43,2925);
   electron_theta_aftercut__4->SetBinContent(44,2728);
   electron_theta_aftercut__4->SetBinContent(45,2720);
   electron_theta_aftercut__4->SetBinContent(46,2556);
   electron_theta_aftercut__4->SetBinContent(47,2322);
   electron_theta_aftercut__4->SetBinContent(48,2249);
   electron_theta_aftercut__4->SetBinContent(49,1992);
   electron_theta_aftercut__4->SetBinContent(50,1879);
   electron_theta_aftercut__4->SetBinContent(51,1714);
   electron_theta_aftercut__4->SetBinContent(52,1668);
   electron_theta_aftercut__4->SetBinContent(53,1551);
   electron_theta_aftercut__4->SetBinContent(54,1420);
   electron_theta_aftercut__4->SetBinContent(55,1377);
   electron_theta_aftercut__4->SetBinContent(56,1345);
   electron_theta_aftercut__4->SetBinContent(57,1132);
   electron_theta_aftercut__4->SetBinContent(58,1089);
   electron_theta_aftercut__4->SetBinContent(59,957);
   electron_theta_aftercut__4->SetBinContent(60,897);
   electron_theta_aftercut__4->SetBinContent(61,884);
   electron_theta_aftercut__4->SetBinContent(62,832);
   electron_theta_aftercut__4->SetBinContent(63,730);
   electron_theta_aftercut__4->SetBinContent(64,685);
   electron_theta_aftercut__4->SetBinContent(65,708);
   electron_theta_aftercut__4->SetBinContent(66,586);
   electron_theta_aftercut__4->SetBinContent(67,534);
   electron_theta_aftercut__4->SetBinContent(68,538);
   electron_theta_aftercut__4->SetBinContent(69,438);
   electron_theta_aftercut__4->SetBinContent(70,427);
   electron_theta_aftercut__4->SetBinContent(71,417);
   electron_theta_aftercut__4->SetBinContent(72,384);
   electron_theta_aftercut__4->SetBinContent(73,305);
   electron_theta_aftercut__4->SetBinContent(74,323);
   electron_theta_aftercut__4->SetBinContent(75,296);
   electron_theta_aftercut__4->SetBinContent(76,275);
   electron_theta_aftercut__4->SetBinContent(77,261);
   electron_theta_aftercut__4->SetBinContent(78,234);
   electron_theta_aftercut__4->SetBinContent(79,220);
   electron_theta_aftercut__4->SetBinContent(80,198);
   electron_theta_aftercut__4->SetBinContent(81,198);
   electron_theta_aftercut__4->SetBinContent(82,161);
   electron_theta_aftercut__4->SetBinContent(83,167);
   electron_theta_aftercut__4->SetBinContent(84,149);
   electron_theta_aftercut__4->SetBinContent(85,142);
   electron_theta_aftercut__4->SetBinContent(86,125);
   electron_theta_aftercut__4->SetBinContent(87,120);
   electron_theta_aftercut__4->SetBinContent(88,121);
   electron_theta_aftercut__4->SetBinContent(89,109);
   electron_theta_aftercut__4->SetBinContent(90,93);
   electron_theta_aftercut__4->SetBinContent(91,109);
   electron_theta_aftercut__4->SetBinContent(92,93);
   electron_theta_aftercut__4->SetBinContent(93,87);
   electron_theta_aftercut__4->SetBinContent(94,67);
   electron_theta_aftercut__4->SetBinContent(95,62);
   electron_theta_aftercut__4->SetBinContent(96,60);
   electron_theta_aftercut__4->SetBinContent(97,64);
   electron_theta_aftercut__4->SetBinContent(98,52);
   electron_theta_aftercut__4->SetBinContent(99,70);
   electron_theta_aftercut__4->SetBinContent(100,59);
   electron_theta_aftercut__4->SetBinContent(101,61);
   electron_theta_aftercut__4->SetBinContent(102,49);
   electron_theta_aftercut__4->SetBinContent(103,61);
   electron_theta_aftercut__4->SetBinContent(104,47);
   electron_theta_aftercut__4->SetBinContent(105,37);
   electron_theta_aftercut__4->SetBinContent(106,32);
   electron_theta_aftercut__4->SetBinContent(107,22);
   electron_theta_aftercut__4->SetBinContent(108,35);
   electron_theta_aftercut__4->SetBinContent(109,29);
   electron_theta_aftercut__4->SetBinContent(110,29);
   electron_theta_aftercut__4->SetBinContent(111,21);
   electron_theta_aftercut__4->SetBinContent(112,24);
   electron_theta_aftercut__4->SetBinContent(113,19);
   electron_theta_aftercut__4->SetBinContent(114,30);
   electron_theta_aftercut__4->SetBinContent(115,22);
   electron_theta_aftercut__4->SetBinContent(116,26);
   electron_theta_aftercut__4->SetBinContent(117,20);
   electron_theta_aftercut__4->SetBinContent(118,15);
   electron_theta_aftercut__4->SetBinContent(119,10);
   electron_theta_aftercut__4->SetBinContent(120,13);
   electron_theta_aftercut__4->SetBinContent(121,20);
   electron_theta_aftercut__4->SetBinContent(122,10);
   electron_theta_aftercut__4->SetBinContent(123,12);
   electron_theta_aftercut__4->SetBinContent(124,12);
   electron_theta_aftercut__4->SetBinContent(125,8);
   electron_theta_aftercut__4->SetBinContent(126,7);
   electron_theta_aftercut__4->SetBinContent(127,10);
   electron_theta_aftercut__4->SetBinContent(128,10);
   electron_theta_aftercut__4->SetBinContent(129,11);
   electron_theta_aftercut__4->SetBinContent(130,8);
   electron_theta_aftercut__4->SetBinContent(131,7);
   electron_theta_aftercut__4->SetBinContent(132,7);
   electron_theta_aftercut__4->SetBinContent(133,6);
   electron_theta_aftercut__4->SetBinContent(134,5);
   electron_theta_aftercut__4->SetBinContent(135,4);
   electron_theta_aftercut__4->SetBinContent(136,7);
   electron_theta_aftercut__4->SetBinContent(137,8);
   electron_theta_aftercut__4->SetBinContent(138,4);
   electron_theta_aftercut__4->SetBinContent(139,4);
   electron_theta_aftercut__4->SetBinContent(140,3);
   electron_theta_aftercut__4->SetBinContent(141,6);
   electron_theta_aftercut__4->SetBinContent(142,4);
   electron_theta_aftercut__4->SetBinContent(143,6);
   electron_theta_aftercut__4->SetBinContent(144,4);
   electron_theta_aftercut__4->SetBinContent(145,2);
   electron_theta_aftercut__4->SetBinContent(146,4);
   electron_theta_aftercut__4->SetBinContent(147,3);
   electron_theta_aftercut__4->SetBinContent(148,6);
   electron_theta_aftercut__4->SetBinContent(149,3);
   electron_theta_aftercut__4->SetBinContent(150,1);
   electron_theta_aftercut__4->SetBinContent(151,1);
   electron_theta_aftercut__4->SetBinContent(152,2);
   electron_theta_aftercut__4->SetBinContent(153,3);
   electron_theta_aftercut__4->SetBinContent(154,2);
   electron_theta_aftercut__4->SetBinContent(155,1);
   electron_theta_aftercut__4->SetBinContent(156,2);
   electron_theta_aftercut__4->SetBinContent(157,3);
   electron_theta_aftercut__4->SetBinContent(158,2);
   electron_theta_aftercut__4->SetBinContent(159,2);
   electron_theta_aftercut__4->SetBinContent(161,1);
   electron_theta_aftercut__4->SetBinContent(162,1);
   electron_theta_aftercut__4->SetBinContent(163,1);
   electron_theta_aftercut__4->SetBinContent(164,1);
   electron_theta_aftercut__4->SetBinContent(165,1);
   electron_theta_aftercut__4->SetBinContent(166,1);
   electron_theta_aftercut__4->SetMaximum(4142.4);
   electron_theta_aftercut__4->SetEntries(77712);
   electron_theta_aftercut__4->SetDirectory(nullptr);
   
   TPaveStats *ptstats = new TPaveStats(0.75,0.835,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0c5da5");
   ptstats->SetTextColor(ci);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Entries = 77712  ");
   ptstats_LaTex = ptstats->AddText("Mean  =   8.38");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  2.536");
   ptstats->SetOptStat(1110);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   electron_theta_aftercut__4->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(electron_theta_aftercut__4);

   ci = TColor::GetColor("#0c5da5");
   electron_theta_aftercut__4->SetLineColor(ci);
   electron_theta_aftercut__4->GetXaxis()->SetTitle("#theta_{e} [Deg.]");
   electron_theta_aftercut__4->GetXaxis()->SetLabelFont(42);
   electron_theta_aftercut__4->GetXaxis()->SetTitleSize(0.05);
   electron_theta_aftercut__4->GetXaxis()->SetTitleOffset(1);
   electron_theta_aftercut__4->GetXaxis()->SetTitleFont(42);
   electron_theta_aftercut__4->GetYaxis()->SetLabelFont(42);
   electron_theta_aftercut__4->GetYaxis()->SetTitleFont(42);
   electron_theta_aftercut__4->GetZaxis()->SetLabelFont(42);
   electron_theta_aftercut__4->GetZaxis()->SetTitleOffset(1);
   electron_theta_aftercut__4->GetZaxis()->SetTitleFont(42);
   electron_theta_aftercut__4->Draw("histo");
   
   ptstats = new TPaveStats(0.75,0.835,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);

   ci = TColor::GetColor("#0c5da5");
   ptstats->SetTextColor(ci);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("Entries = 77712  ");
   ptstats_LaTex = ptstats->AddText("Mean  =   8.38");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  2.536");
   ptstats->SetOptStat(1110);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   c1->Modified();
   c1->SetSelected(c1);
}
