#ifdef __CLING__
#pragma cling optimize(0)
#endif
void pion_plus_theta_aftercut()
{
//=========Macro generated from canvas: c1/
//=========  (Fri Oct 25 11:19:07 2024) by ROOT version 6.30/04
   TCanvas *c1 = new TCanvas("c1", "",0,0,800,600);
   gStyle->SetOptFit(1);
   c1->SetHighLightColor(2);
   c1->Range(-28.42105,-927.0947,208.4211,6798.695);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetLeftMargin(0.12);
   c1->SetRightMargin(0.12);
   c1->SetTopMargin(0.12);
   c1->SetBottomMargin(0.12);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderMode(0);
   
   TH1F *pion_plus_theta_aftercut__9 = new TH1F("pion_plus_theta_aftercut__9","",200,0,180);
   pion_plus_theta_aftercut__9->SetBinContent(1,1);
   pion_plus_theta_aftercut__9->SetBinContent(3,11);
   pion_plus_theta_aftercut__9->SetBinContent(4,31);
   pion_plus_theta_aftercut__9->SetBinContent(5,79);
   pion_plus_theta_aftercut__9->SetBinContent(6,330);
   pion_plus_theta_aftercut__9->SetBinContent(7,2330);
   pion_plus_theta_aftercut__9->SetBinContent(8,3842);
   pion_plus_theta_aftercut__9->SetBinContent(9,4239);
   pion_plus_theta_aftercut__9->SetBinContent(10,4685);
   pion_plus_theta_aftercut__9->SetBinContent(11,4701);
   pion_plus_theta_aftercut__9->SetBinContent(12,4876);
   pion_plus_theta_aftercut__9->SetBinContent(13,4893);
   pion_plus_theta_aftercut__9->SetBinContent(14,4731);
   pion_plus_theta_aftercut__9->SetBinContent(15,4617);
   pion_plus_theta_aftercut__9->SetBinContent(16,4322);
   pion_plus_theta_aftercut__9->SetBinContent(17,3928);
   pion_plus_theta_aftercut__9->SetBinContent(18,3571);
   pion_plus_theta_aftercut__9->SetBinContent(19,3217);
   pion_plus_theta_aftercut__9->SetBinContent(20,2884);
   pion_plus_theta_aftercut__9->SetBinContent(21,2661);
   pion_plus_theta_aftercut__9->SetBinContent(22,2322);
   pion_plus_theta_aftercut__9->SetBinContent(23,2117);
   pion_plus_theta_aftercut__9->SetBinContent(24,1939);
   pion_plus_theta_aftercut__9->SetBinContent(25,1681);
   pion_plus_theta_aftercut__9->SetBinContent(26,1605);
   pion_plus_theta_aftercut__9->SetBinContent(27,1405);
   pion_plus_theta_aftercut__9->SetBinContent(28,1288);
   pion_plus_theta_aftercut__9->SetBinContent(29,1100);
   pion_plus_theta_aftercut__9->SetBinContent(30,944);
   pion_plus_theta_aftercut__9->SetBinContent(31,883);
   pion_plus_theta_aftercut__9->SetBinContent(32,809);
   pion_plus_theta_aftercut__9->SetBinContent(33,757);
   pion_plus_theta_aftercut__9->SetBinContent(34,697);
   pion_plus_theta_aftercut__9->SetBinContent(35,639);
   pion_plus_theta_aftercut__9->SetBinContent(36,629);
   pion_plus_theta_aftercut__9->SetBinContent(37,610);
   pion_plus_theta_aftercut__9->SetBinContent(38,577);
   pion_plus_theta_aftercut__9->SetBinContent(39,592);
   pion_plus_theta_aftercut__9->SetBinContent(40,568);
   pion_plus_theta_aftercut__9->SetBinContent(41,538);
   pion_plus_theta_aftercut__9->SetBinContent(42,476);
   pion_plus_theta_aftercut__9->SetBinContent(43,544);
   pion_plus_theta_aftercut__9->SetBinContent(44,490);
   pion_plus_theta_aftercut__9->SetBinContent(45,502);
   pion_plus_theta_aftercut__9->SetBinContent(46,483);
   pion_plus_theta_aftercut__9->SetBinContent(47,477);
   pion_plus_theta_aftercut__9->SetBinContent(48,440);
   pion_plus_theta_aftercut__9->SetBinContent(49,470);
   pion_plus_theta_aftercut__9->SetBinContent(50,396);
   pion_plus_theta_aftercut__9->SetBinContent(51,395);
   pion_plus_theta_aftercut__9->SetBinContent(52,371);
   pion_plus_theta_aftercut__9->SetBinContent(53,337);
   pion_plus_theta_aftercut__9->SetBinContent(54,295);
   pion_plus_theta_aftercut__9->SetBinContent(55,292);
   pion_plus_theta_aftercut__9->SetBinContent(56,268);
   pion_plus_theta_aftercut__9->SetBinContent(57,232);
   pion_plus_theta_aftercut__9->SetBinContent(58,239);
   pion_plus_theta_aftercut__9->SetBinContent(59,219);
   pion_plus_theta_aftercut__9->SetBinContent(60,190);
   pion_plus_theta_aftercut__9->SetBinContent(61,189);
   pion_plus_theta_aftercut__9->SetBinContent(62,159);
   pion_plus_theta_aftercut__9->SetBinContent(63,156);
   pion_plus_theta_aftercut__9->SetBinContent(64,151);
   pion_plus_theta_aftercut__9->SetBinContent(65,145);
   pion_plus_theta_aftercut__9->SetBinContent(66,126);
   pion_plus_theta_aftercut__9->SetBinContent(67,121);
   pion_plus_theta_aftercut__9->SetBinContent(68,105);
   pion_plus_theta_aftercut__9->SetBinContent(69,106);
   pion_plus_theta_aftercut__9->SetBinContent(70,103);
   pion_plus_theta_aftercut__9->SetBinContent(71,104);
   pion_plus_theta_aftercut__9->SetBinContent(72,88);
   pion_plus_theta_aftercut__9->SetBinContent(73,90);
   pion_plus_theta_aftercut__9->SetBinContent(74,76);
   pion_plus_theta_aftercut__9->SetBinContent(75,64);
   pion_plus_theta_aftercut__9->SetBinContent(76,75);
   pion_plus_theta_aftercut__9->SetBinContent(77,65);
   pion_plus_theta_aftercut__9->SetBinContent(78,67);
   pion_plus_theta_aftercut__9->SetBinContent(79,60);
   pion_plus_theta_aftercut__9->SetBinContent(80,58);
   pion_plus_theta_aftercut__9->SetBinContent(81,46);
   pion_plus_theta_aftercut__9->SetBinContent(82,40);
   pion_plus_theta_aftercut__9->SetBinContent(83,48);
   pion_plus_theta_aftercut__9->SetBinContent(84,39);
   pion_plus_theta_aftercut__9->SetBinContent(85,43);
   pion_plus_theta_aftercut__9->SetBinContent(86,26);
   pion_plus_theta_aftercut__9->SetBinContent(87,31);
   pion_plus_theta_aftercut__9->SetBinContent(88,36);
   pion_plus_theta_aftercut__9->SetBinContent(89,31);
   pion_plus_theta_aftercut__9->SetBinContent(90,30);
   pion_plus_theta_aftercut__9->SetBinContent(91,27);
   pion_plus_theta_aftercut__9->SetBinContent(92,14);
   pion_plus_theta_aftercut__9->SetBinContent(93,23);
   pion_plus_theta_aftercut__9->SetBinContent(94,18);
   pion_plus_theta_aftercut__9->SetBinContent(95,23);
   pion_plus_theta_aftercut__9->SetBinContent(96,19);
   pion_plus_theta_aftercut__9->SetBinContent(97,17);
   pion_plus_theta_aftercut__9->SetBinContent(98,20);
   pion_plus_theta_aftercut__9->SetBinContent(99,13);
   pion_plus_theta_aftercut__9->SetBinContent(100,13);
   pion_plus_theta_aftercut__9->SetBinContent(101,14);
   pion_plus_theta_aftercut__9->SetBinContent(102,11);
   pion_plus_theta_aftercut__9->SetBinContent(103,6);
   pion_plus_theta_aftercut__9->SetBinContent(104,13);
   pion_plus_theta_aftercut__9->SetBinContent(105,12);
   pion_plus_theta_aftercut__9->SetBinContent(106,8);
   pion_plus_theta_aftercut__9->SetBinContent(107,6);
   pion_plus_theta_aftercut__9->SetBinContent(108,7);
   pion_plus_theta_aftercut__9->SetBinContent(109,6);
   pion_plus_theta_aftercut__9->SetBinContent(110,10);
   pion_plus_theta_aftercut__9->SetBinContent(111,4);
   pion_plus_theta_aftercut__9->SetBinContent(112,3);
   pion_plus_theta_aftercut__9->SetBinContent(113,2);
   pion_plus_theta_aftercut__9->SetBinContent(114,5);
   pion_plus_theta_aftercut__9->SetBinContent(115,1);
   pion_plus_theta_aftercut__9->SetBinContent(116,3);
   pion_plus_theta_aftercut__9->SetBinContent(117,3);
   pion_plus_theta_aftercut__9->SetBinContent(118,3);
   pion_plus_theta_aftercut__9->SetBinContent(119,4);
   pion_plus_theta_aftercut__9->SetBinContent(120,3);
   pion_plus_theta_aftercut__9->SetBinContent(121,1);
   pion_plus_theta_aftercut__9->SetBinContent(122,4);
   pion_plus_theta_aftercut__9->SetBinContent(123,2);
   pion_plus_theta_aftercut__9->SetBinContent(124,1);
   pion_plus_theta_aftercut__9->SetBinContent(126,2);
   pion_plus_theta_aftercut__9->SetBinContent(127,2);
   pion_plus_theta_aftercut__9->SetBinContent(128,1);
   pion_plus_theta_aftercut__9->SetBinContent(129,1);
   pion_plus_theta_aftercut__9->SetBinContent(130,1);
   pion_plus_theta_aftercut__9->SetBinContent(132,1);
   pion_plus_theta_aftercut__9->SetBinContent(135,1);
   pion_plus_theta_aftercut__9->SetBinContent(137,1);
   pion_plus_theta_aftercut__9->SetMaximum(5871.6);
   pion_plus_theta_aftercut__9->SetEntries(91572);
   pion_plus_theta_aftercut__9->SetDirectory(nullptr);
   
   TPaveStats *ptstats = new TPaveStats(0.75,0.835,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0c5da5");
   ptstats->SetTextColor(ci);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Entries = 91572  ");
   ptstats_LaTex = ptstats->AddText("Mean  =  19.24");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  13.48");
   ptstats->SetOptStat(1110);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   pion_plus_theta_aftercut__9->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(pion_plus_theta_aftercut__9);

   ci = TColor::GetColor("#0c5da5");
   pion_plus_theta_aftercut__9->SetLineColor(ci);
   pion_plus_theta_aftercut__9->GetXaxis()->SetTitle("#theta_{#pi^{+}} [Deg.]");
   pion_plus_theta_aftercut__9->GetXaxis()->SetLabelFont(42);
   pion_plus_theta_aftercut__9->GetXaxis()->SetTitleSize(0.05);
   pion_plus_theta_aftercut__9->GetXaxis()->SetTitleOffset(1);
   pion_plus_theta_aftercut__9->GetXaxis()->SetTitleFont(42);
   pion_plus_theta_aftercut__9->GetYaxis()->SetLabelFont(42);
   pion_plus_theta_aftercut__9->GetYaxis()->SetTitleFont(42);
   pion_plus_theta_aftercut__9->GetZaxis()->SetLabelFont(42);
   pion_plus_theta_aftercut__9->GetZaxis()->SetTitleOffset(1);
   pion_plus_theta_aftercut__9->GetZaxis()->SetTitleFont(42);
   pion_plus_theta_aftercut__9->Draw("histo");
   
   ptstats = new TPaveStats(0.75,0.835,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);

   ci = TColor::GetColor("#0c5da5");
   ptstats->SetTextColor(ci);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("Entries = 91572  ");
   ptstats_LaTex = ptstats->AddText("Mean  =  19.24");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  13.48");
   ptstats->SetOptStat(1110);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   c1->Modified();
   c1->SetSelected(c1);
}
